version: '{build}'
max_jobs: 4

branches:
  only:
    - master
    - release

image:
- Visual Studio 2019
- Visual Studio 2017

configuration:
- Release

cache:
  - VulkanSDK.exe

# target only 64-bit for now
platform:
- x64

# setup Vulkan and build project
install:
  - echo Downloading Vulkan ...
  - echo Running on %PLATFORM% as %CONFIGURATION%
  - if not exist VulkanSDK.exe curl -L --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.2.141.2/windows/VulkanSDK-1.2.141.2-Installer.exe?Human=true
  - VulkanSDK.exe /S
  - cmake --version
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - mkdir -p build && cd build
  - cmake .. -A %PLATFORM% -DENABLE_MULTICORE=OFF -DIS_RELEASE=ON

before_build:
  - ps: $env:VULKAN_SDK="C:/VulkanSDK/1.2.141.2"

build:
  parallel: true
  project: build/CarbonEngine.sln
  verbosity: normal
